global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    scrape_interval: 10s
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'user-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'product-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['product-service:8082']

  - job_name: 'notification-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['notification-service:8083']